// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgbvmepolawsdbssdpmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYnZtZXBvbGF3c2Ric3NkcG1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0ODA5ODgsImV4cCI6MjA1MDA1Njk4OH0.xDs75WZyhfZiFt9eY_GnGrhGmL2K8g7ynhgfiS2JcTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);